<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="styles/footer.css"></head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<body>
<footer class="my-footer">
    <div>
        <ul class="list-inline">
            <li class="list-inline-item"><a href="#"><small>Home</small></a></li>
            <li class="list-inline-item"><a href="#"><small>Services</small></a></li>
            <li class="list-inline-item"><a href="#"><small>Terms</small></a></li>
            <li class="list-inline-item"><a href="#"><small>Privacy Policy</small></a></li>
        </ul>
        <br>
        <hr style="width: 30%; margin: -30px auto">
        <p class="copyright" style="margin-top: 40px; color: white"><small>Monster Musk 2023</small></p>
    </div>
</footer>
</body>
</html>